### PR TITLE
#TWSThreeTierAppChallenge

### PR DESCRIPTION
**Pull request by st662**
Notable accomplishments:

1. Terraform for AWS EKS Cluster:
- Established an AWS EKS Cluster and improved the code by implementing a Kubernetes Cluster-Autoscaler for Node Auto-Scaling.
- Additionally, integrated an EBS-CSI driver add-on to facilitate the creation of Dynamic EBS Volumes for MongoDB data persistence and incorporated an ALB-Controller for Application Routing through K8s Ingress.

2. Kubernetes Enhancements:
- Implemented the deployment of a MongoDB StatefulSet to efficiently oversee the MongoDB database within the Kubernetes cluster.
- Established a StorageClass to enable dynamic provisioning of PersistentVolumes and PersistentVolumeClaims, enhancing storage management capabilities.

3. Implemented CI/CD using Jenkins:
- Developed Groovy scripts for constructing Docker images using Dockerfiles and subsequently pushing them to AWS ECR.
- Additionally, I customized Dockerfiles by incorporating a custom user and implementing a multi-stage build process.
- Established a dedicated Jenkins ServiceAccount, utilizing Kubernetes Role-Based Access Control (RBAC), to deploy this application to AWS EKS.
- Implemented comprehensive automation, including the automatic updating of Kubernetes images in the manifest file, streamlining the entire process from image building to deployment.

### CODE REVIEW

**Comment by LondheShubham153** [comment]
great,
can you use modules in Terraform to reduc the size of TF files?

**Comment by st662** [comment]
> great, can you use modules in Terraform to reduce the size of TF files?

I thought writing tf files from scratch would be understood by someone who knows just the basics of terraform. No problem, I will update with Modules.

**Comment by LondheShubham153** [comment]
conflicts hai

**Comment by st662** [comment]
Hello sir,
I will resolve them as soon as possible.

**Comment by st662** [comment]
Hello sir, I took the Enneagram test you posted on your LinkedIn. Let
me know what you think. I will share the results with you.

**Pull request closed without merging**
